[package]
name = "reqwest-async"
version = "0.1.0"
authors = ["Foo <foo@bar.com>"]

[dependencies]
serde_json = "1.0.6"
serde = "1.0.21"
serde_derive = "1.0.21"
futures = "0.1.17"
tokio-core = "0.1.10"

[dependencies.reqwest]
version = "0.8.1"
features = ["unstable"]
